services:
  user-service:
    image: "postgres:latest"
    container_name: "user-service"
    restart: always
    environment:
      - "POSTGRES_DB=user_db"
      - "POSTGRES_USER=abdullah"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"

  media-service:
    image: "postgres:latest"
    container_name: "media-service"
    restart: always
    environment:
      - "POSTGRES_DB=media_db"
      - "POSTGRES_USER=abdullah"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5433:5432"

  rabbitmq:
    image: "rabbitmq:management-alpine"
    container_name: "rabbitmq"
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
    ports:
      - "15672:15672"
      - "5672:5672"